# Generated by Django 5.1.4 on 2025-02-17 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=255)),
                ('industry_rating', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('market_value', models.FloatField()),
                ('percentage_to_nav', models.FloatField()),
                ('isin', models.CharField(max_length=50)),
                ('yield_percentage', models.FloatField(blank=True, null=True)),
                ('ytc', models.FloatField(blank=True, null=True)),
                ('instrument_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_market_value', models.FloatField()),
                ('equity_total', models.FloatField()),
                ('debt_total', models.FloatField()),
                ('other_total', models.FloatField()),
                ('portfolio_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CashEquivalents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.portfolio')),
            ],
        ),
    ]
