# Generated by Django 5.1.4 on 2025-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_market_value',
            field=models.FloatField(default=0),
        ),
    ]
