# Generated by Django 5.1.4 on 2025-02-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_alter_portfolio_total_market_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='debt_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='equity_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='other_total',
            field=models.FloatField(default=0),
        ),
    ]
